### ISSUE TITLE
Зависают задания в статусе ОжидаетВыделенногоИсполнителя

### ISSUE THREAD

**Issue by berezdetsky** [wizi4d/TaskManagerFor1C#11]
Если запустить задание методом ДобавитьЗаданиеВнеОчереди, а фоновое задание исполнителя не запустится, задание зависает в статусе ОжидаетВыделенногоИсполнителя навсегда. При сбоях сервера приложений проблема становится массовой.

Предлагаю сбрасывать статус ОжидаетВыделенногоИсполнителя в Ожидает, если прошло больше минуты с момента добавления задания.

**Comment by wizi4d** [comment]
Есть идеи, как воспроизвести ситуацию в тесте? Я не про предлагаемый вариант реализации, а про ситуацию в целом.

**Comment by berezdetsky** [comment]
В тесте - добавить запись в регистр врукопашную. Минус - надо знать, как устроен чёрный ящик. В реале я наблюдал ситуацию как следствие двух разных ошибок платформы.

На предлагаемый вариант забей, написал не подумав.

**Comment by wizi4d** [comment]
Если честно, я пока ничего лучше предложенного тобой варианта не придумал...

**Comment by berezdetsky** [comment]
Просто я тебя с мысли сбил, не дав разобраться самому.. :) Так то решений несколько есть.

**Comment by wizi4d** [comment]
Меня не так то просто сбить с мысли :)
Если есть еще варианты, пиши. Коллективный разум рулит, вместе выработаем лучшее решение.

**Comment by berezdetsky** [comment]
Ещё вариант: добавить условие в запрос ожидающих. Относительно предыдущего варианта:
- сэкономит запись (изменение статуса);
- нагрузку не добавит, т.к. эти задания всё равно надо искать.

Но я глубоко не копал, на самом деле.

**Comment by berezdetsky** [comment]
ДобавитьЗаданиеВнеОчереди запускает задание даже если менеджер выключен. Если добавить контроль запуска, появится возможность тестировать ситуацию используя штатный интерфейс.

**Comment by wizi4d** [comment]
@berezdetsky поможешь с тестированием? Develop ветка, собрать можно в 8.3.7

**Comment by berezdetsky** [comment]
Да, в понедельник.

**Comment by berezdetsky** [comment]
Протестировал, работает.

Теперь надо не забыть удалить неактуальные задания при обновлении. :)
