### ISSUE TITLE
разбор ошибочных ситуаций

### ISSUE THREAD

**Issue by berezdetsky** [wizi4d/TaskManagerFor1C#12]
Иногда бывает нужно узнать, с какими параметрами было запущено задание. Просьба добавить:
- запись ключа задания в ЖР в Исполнитель_Выполнение (для поиска задания по номеру сеанса);
- форму записи регистра мзЗадания с отображением параметров.

**Comment by berezdetsky** [comment]
Пример формы от Жени Крупина могу прислать. Там параметры выводятся как xml.

**Comment by artbear** [comment]
+1

**Comment by wizi4d** [comment]
Оптимально сделать самим и прислать пуллреквест :smile:

**Comment by berezdetsky** [comment]
Пуллреквест с формой сделал.

**Comment by wizi4d** [comment]
А зачем запись ключа задания в ЖР? Что это даст?

**Comment by berezdetsky** [comment]
Типовой сценарий:
- по ЖР ищем проблему;
- по номеру сеанса определяем ключ задания;
- по ключу смотрим параметры;
- идём дебажить.

Как то так..
Но если писать код без ошибок - это всё не нужно, конечно. :)
