### ISSUE TITLE
Статус проекта и порядок работы

### ISSUE THREAD

**Issue by ghost** [wizi4d/TaskManagerFor1C#2]
Интересует 3 вопроса:
- будет ли проект развиваться
- какой порядок коллективной разработки, если она подразумевается
- какой порядок регистрации пожеланий к развитию или недочетов в реализации

;-)

**Comment by wizi4d** [comment]
1) Проект может развиваться, если возникнут интересные идеи по развитию.
2) Для начала можно через пуллреквест, дальше будет видно.
3) Так же как с текущим вопросом, issue

**Comment by ghost** [comment]
1. то есть идей нет ?
2. как я сделаю pull request - если исходники не планируются ?

**Comment by wizi4d** [comment]
1. Почва для появление идей - реальная потребность, которая не покрывается текущей функциональностью. Сейчас продукт покрывает все мои потребности. Будут озвучены потребности от других людей, будут идеи по их удовлетворению.
2. cf файл сам по себе исходник. Как наличие "исходников" в виде текстовой выгрузки поможет проводить пуллреквест?

Алексей, давно уже стало понятно, что у нас разные взгляды на ведение хранилищ проектов 1С.
Моя позиция простая:
1. Никто не мешает положить текстовики одни, а cf файл с совсем иным содержанием. Не по злому умыслу, а просто по ошибке.
2. Имеет смысл вести хранилище с текстовиками при выполнении условия, что хранилище содержит ТОЛЬКО текстовики и финальный продукт может быть собран из этих текстовиков. При этом инструменты по сборке должны быть стабильными. Текущие средства по сборке платформо-зависимы и не всегда ведут себя стабильно.

P.S. Когда ты наконец признаешь, что люди могут иметь собственное мнение, которое не всегда совпадает с твоим? :)

**Comment by ghost** [comment]
@wizi4d тебя ввело в заблуждение что написал "я". Де-факто я лишь оттранслировал вопрос коллег, которые пока не научились работать с github
