### ISSUE TITLE
Добавить константу для учета максимальных запусков неудачных задач. 

### ISSUE THREAD

**Issue by pumbaEO** [wizi4d/TaskManagerFor1C#3]
Как пользователь, я хочу сломанные/падающие задания запускать не более чем n раз, т.е в случаи ошибочного кода у нас сейчас остается куча задач уже неактуальных, но при этом каждый раз выполняющихся.

**Comment by wizi4d** [comment]
Что должно произойти с таким заданием? Должно ли оно как-то маркироваться?

Изначально предполагал, что ВСЕ задачи должны быть выполненными. Если по какой-то причине  накапливаются задания, которые не могут выполниться, это предмет для расследования и по завершению расследования разработчик их сам отменит или они все же выполняться после внесенных исправлений.

**Comment by wizi4d** [comment]
Т.к. в метод обработчик структура параметров передается расширенной ключом задания, то в качестве альтернативного варианта предлагаю в прикладном коде самостоятельно считать попытки. Гибкость решения в том, что каждый метод обработчик сможет сам принимать решение, когда ему перестать выполняться.

**Comment by artbear** [comment]
@wizi4d Предложи вариант реализации, псевдо-код или код 1С

**Comment by wizi4d** [comment]
```
Процедура НекоеЗадание(Параметры) Экспорт
    КоличествоПопытокВыполнения = Хелперы.ПолучитьКоличествоПопытокВыполнения(Параметры.КлючЗадания);
    Если КоличествоПопытокВыполнения >= 10 Тогда
        Возврат;
    КонецЕсли;
    ...
    // Основной код
КонецПроцедуры
```

Возможно этот самый метод хелпер имеет смысл добавить в API подсистемы. Пока же можно самому посылать запрос к регистру с заданиями и по ключу получить КоличествоПопытокВыполения

**Comment by wizi4d** [comment]
Возникла мысль, которая вроде как покрывает требуемую функциональность, при этом не накладывает ограничений и дополнительно расширяет функционал библиотеки.
Сделать регистр с настройками методов-обработчиков. В качестве полезных настроек пока придумалось следующее:
- Количество попыток выполнения - через какое количество попыток переставать выполнять задание с ошибкой;
- Пауза перед новой попыткой - период времени в секундах, через который нужно предпринимать новую попытку выполнения задания с ошибкой.

Если есть еще идеи настроек, пишите. Обязательно приводить примеры, когда предложенные настройки могут пригодиться.

**Comment by artbear** [comment]
В этом регистре измерением будет наименование метода обработчика?

**Comment by wizi4d** [comment]
да
