### ISSUE TITLE
Возможность ограничения количества исполнителей для вида операции

### ISSUE THREAD

**Issue by artbear** [wizi4d/TaskManagerFor1C#4]
Хотелось бы получить возможность ограничения количества исполнителей для вида операции.
Эта функциональность нужна для повышения многопоточности.
Для конкурирующих задач ограничиваем число потоков, в это время могут выполняться потоки по другим операциям.

Например, есть загрузка справочников 2-х неконкурирующих наборов данных: Номенклатура и Контрагентов с записью необходимых подчиненных справочников и регистров.
Загрузка конкретных номенклатур/контрагентов может конкурировать, например, по регистрам сведений и т.п.

Сейчас в подсистеме можно создать нужное число потоков и они начнут выполняться в определенном порядке, например, сначала будут загружаться потоки по контрагентам, а только потом номенклатура. В итоге получаем, пока первый вид операций не закончится и не освободит исполнителей, вторая загрузка не начнется :(

Хотелось бы разделить загрузку на 2 части - 4 потока на контрагентов и 4 потока на номенклатуру.

@wizi4d @EvilBeaver что скажете?

**Comment by wizi4d** [comment]
Т.е. задания берутся как и раньше сверху, только для конкретных методы-обработчики квотируются?
Идея нравится и выглядит полезной. Особенно для заданий, которые сильно нагружают систему.

**Comment by artbear** [comment]
Да, именно

**Comment by artbear** [comment]
Да, именно в случае "тяжелых" заданий они могут заблокировать все прочие задания и вообще нагрузить систему вплоть до отказа.

**Comment by EvilBeaver** [comment]
А как могла бы выглядеть настройка квотирования? Какие параметры?

**Comment by artbear** [comment]
Сценарии:
1. каждый вид операции в порядке очереди захватывает такую квоту, какая установлена в настройках этого вида операции (не больше общей квоты на исполнителей). следующие операции захватывают себе остаток от квоты.
2. для каждого вида операции задается процент от общего числа исполнителей. если общее число исполнителей меняется, меняется и количество исполнителей на вид операции
3. смешанный - для каждого вида операций задается максимум исполнителей на вид операции и процент об общего числа. при назначении исполнителя разрешенное число исполнителей рассчитывается от минимума от 2-х чисел (1-заданного максимума исполнителей на вид и 2-рассчитанного числа исполнителей = процент от общего числа исполнителей) за минусом уже назначенных исполнителей на этот вид операции.

ИМХО 3-й вариант самый удобный и масштабируемый.

**Comment by wizi4d** [comment]
Решил остановиться, на собственном варианте:
Для каждого метода обработчика указывается ограничение на количество исполнителей.
Очередь разгребается по старым правилам - сначала задания, которые еще не брались в работу с минимальным периодом и ссылкой. Новым поведением будет то, что если очередное задание из очереди будет с методом-обработчиком достигшем лимита на количество исполнителей (с учетом заданий в работе), то это задание будет пропущено на текущей итерации распределения заданий по исполнителям. При этом свою позицию в очереди задание сохранит.

**Comment by artbear** [comment]
Да, нормальный вариант
Один вопрос остается - как будет решаться вопрос с ограничением количества исполнителей в целом?
Например, в дневное время хочется использовать только 7, а вот в ночное время можно поставить 15
как администратор сможет ограничить общее число потоков?

**Comment by wizi4d** [comment]
Через UI:
"Управлении менеджером заданий" свойство "Ограничение на количество исполнителей"
Программно:
Процедура УстановитьОграничениеПоКоличествуИсполнителей(Знач ОграничениеНаКоличествоИсполнителей) Экспорт

Сделай регламентное задание, которое по расписанию будет менять общее ограничение на количество исполнителей.

**Comment by artbear** [comment]
Это понятно.
Мне непонятно, как ограничение исполнителей по каждому виду обработчика будет связано с ограничением исполнителей в системе ("Управлении менеджером заданий" свойство "Ограничение на количество исполнителей")
Например, 2 обработчика, у одного ограничение 7 исполнителя, у другого 6. Администратор  меняет общее количество исполнителей в системе на 10 (упомянутое свойство).
Вопрос - как будут распределяться исполнители обработчиков для этого сценария ?

**Comment by wizi4d** [comment]
Ответ уже был выше, видимо не сильно понятно получилось. Переформулирую алгоритм:
Каждый раз будет браться верхнее задание из очереди (минимальное количество попыток и минимальный период создания), если на метод нет ограничений или лимит не достигнут, то задание отбирается для выполнения, если лимит достигнут, то откладывается на следующую итерацию распределения заданий по исполнителям.
Пример:

```
Настройки: Общее ограничение - 5, Метод1 - 4, Метод2 - 2;
Очередь выглядит так ('+' отмечено то, что будет взято в работу):
1. Метод1 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 1
2. Метод2 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 1
3. Метод2 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 2
4. Метод1 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 2
5. Метод2   // Общий лимит ОК, персональный лимит НЕ ОК, счетчик принятых = 2
6. Метод2   // Общий лимит ОК, персональный лимит НЕ ОК, счетчик принятых = 2
7. Метод1 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 3
8. Метод2   // Общий лимит НЕ ОК, прекращаем отбор заданий
9. Метод1
10. Метод1
```

**Comment by artbear** [comment]
Сценарий - сначала в очереди добавили все задания по Метод1, а только потом по Метод2.
Не получится ли так, что Метод2 не будет выполняться, пока не закончатся все задания по Метод1?

**Comment by wizi4d** [comment]
```
Настройки: Общее ограничение - 5, Метод1 - 4, Метод2 - 2;

1. Метод1 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 1
2. Метод1 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 2
3. Метод1 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 3
4. Метод1 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 4
5. Метод1   // Общий лимит ОК, персональный лимит НЕ ОК, счетчик принятых = 4
6. Метод2 + // Общий лимит ОК, персональный лимит ОК, счетчик принятых = 1
7. Метод2   // Общий лимит НЕ ОК, прекращаем отбор заданий
8. Метод1
9. Метод2
10. Метод2
```

**Comment by artbear** [comment]
Более реальный сценарий:
Настройки: Общее ограничение - 5, Метод1 - 8, Метод2 - 6;
В этом случае задания Метод2 будет ждать, пока выполнятся все задания Метод1, помещенные в очередь раньше

**Comment by wizi4d** [comment]
Если у тебя задание имеет персональный лимит больше общего лимита, то это задание считай, что безлимитное.

**Comment by artbear** [comment]
Лады, по лимитам все понятно.
Меня предложенная схема устраивает.
Предлагаю перейти к обсуждению приоритетов #5

**Comment by wizi4d** [comment]
Важная ремарка, на задания, которые добавляются через метод `ДобавитьЗаданиеВнеОчереди` никакие ограничения не распространяются.
Тоже самое будет относиться к приоритетам #5

**Comment by artbear** [comment]
Согласен, это правильно
