### ISSUE TITLE
Приоритетность заданий

### ISSUE THREAD

**Issue by artbear** [wizi4d/TaskManagerFor1C#5]
Хотелось бы добавить приоритетность заданий.
Чтобы высокоприоритетные задания не ждали окончания выполнения всех более низкоприоритетных заданий
Связано с #4

**Comment by wizi4d** [comment]
Какой предлагаемый алгоритм сортировки очереди?
Сейчас так:
1. КоличествоПопытокВыполения DESC (чтобы упавшие задания сваливались вниз очереди)
2. Период DESC (период создания задания)

В какое место добавить приоритет?

**Comment by wizi4d** [comment]
Ну и в целом хотелось бы понимать, какую проблему пытаешься решить. Желательно реальный кейс, а не абстрактный.

**Comment by artbear** [comment]
Приоритет добавить сверху, т.е.
0. Приоритет Возр
1. КоличествоПопытокВыполения DESC (чтобы упавшие задания сваливались вниз очереди)
2. Период DESC (период создания задания)

**Comment by artbear** [comment]
Мой сценарий: задача начальной загрузки данных.
Я знаю, что номенклатуры много, она будет грузиться долго, есть еще связанные элементы, которые также не быстро прогрузятся, есть другие справочники, которые грузятся не так долго.
Хотелось бы как можно раньше прогрузить эти "легкие" справочники, чтобы можно было работать с этими справочниками.

**Comment by wizi4d** [comment]
Минус предложенного алгоритма сортировки в том, что приоритетные задания ВСЕГДА будут наверху. Если по какой-то причине они не могут выполниться (например, не доступен внешний ресурс), то они полностью блокируют работу ВСЕХ заданий.

**Comment by artbear** [comment]
Это первый вариант.
Если приоритет передвинуть в середину?
0. КоличествоПопытокВыполения DESC (чтобы упавшие задания сваливались вниз очереди)
1. Приоритет Возр
2. Период DESC (период создания задания)

**Comment by EvilBeaver** [comment]
@wizi4d 

> то они полностью блокируют работу ВСЕХ заданий

Так работает и планировщик потоков ОС. Если есть хотя бы один ожидающий поток с приоритетом 4 (цифра условная), то ни один поток с более низким приоритетом не будет отдан в работу.

Т.е. задачу "голода" низкоприоритетных потоков предлагаю не решать. Если приоритетный поток постоянно падает - ему надо поставить лимит. Превышение лимита - исключение из очереди.

**Comment by wizi4d** [comment]
Ок, пока остановимся на первом предложении Артура:

> Приоритет добавить сверху, т.е.
> 0. Приоритет Возр
> 1. КоличествоПопытокВыполения DESC (чтобы упавшие задания сваливались вниз очереди)
> 2. Период DESC (период создания задания)

Единственное, что предлагаю, так это старшим приоритетом считать бОльший числовой показатель. Не нужно будет делать дополнительные телодвижения, потому что по-умолчанию задание будет иметь наименьший приоритет = 0.
Т.о. получаем:

```
Приоритет ASC
КоличествоПопытокВыполения DESC
Период DESC
```

**Comment by EvilBeaver** [comment]
Если по умолчанию наименьший, то сложно задавать "низкоприоритетные" задания. Отрицательные указывать?

**Comment by artbear** [comment]
ИМХО да, отрицательный приоритет это также приоритет

**Comment by wizi4d** [comment]
Давайте соберем все вместе:

```
Приоритет - значение от -9 до +9, где -9 минимальный приоритет, +9 максимальный

Алгоритм сортировки:
Приоритет ASC
КоличествоПопытокВыполения DESC
Период DESC
```

**Comment by artbear** [comment]
Нормально.
Только зачем -9 и +9 ? неужели ты в коде будешь проверять на попадание в этот отрезок? :)

**Comment by wizi4d** [comment]
Нет, на уровне СУБД ресурс будет число(1) :smile:

**Comment by wizi4d** [comment]
Ошибся когда описывал алгоритм. Правильный выглядит так:

```
Приоритет DESC
КоличествоПопытокВыполения ASC
Период ASC
```
