### ISSUE TITLE
Продумать вопрос с отказом от epf внутри репозитория

### ISSUE THREAD

**Issue by wizi4d** [wizi4d/TaskManagerFor1C#7]
В анонсе 8.3.7 была обозначена функциональность выгрузки/загрузки в текстовые файлы внешних отчетов и обработок. Возможно имеет смысл отказаться от хранения epf внутри репозитория в пользу только текстовых файлов.
Таким образом можно будет свести к минимуму количество ручных действий при пул-реквестах и принимать их прям в вэб-форме гитхаба.
Для упрощения разработки можно подумать над post-merge хуком, который будет автоматически собирать epf файлы в игнорируемую гитом папку после pull в локальном репозитории.

**Comment by narus2** [comment]
Эта функция доступна не только 8.3.7 но и начиная с 8.2 просто в 8.3.7 поддерживается дерево файлов. но для этой задачки не обязательно.

**Comment by wizi4d** [comment]
@narus2 в данной задаче речь не о выгрузке конфигурации в текстовые файлы, а о работе именно с **внешними** обработками (в данном случае это epf файлы с тестами)

**Comment by narus2** [comment]
Ну да согласен ) Тогда могут помочь инструменты типа  https://github.com/pumbaEO/v83unpack.git или встраивать в конфигурацию что не есть красивое решение.

**Comment by wizi4d** [comment]
При работе с v83unpack сами epf файлы нужно хранить в репозитории рядом с исходниками. Суть этого issue в том, чтобы в репо были только текстовики без бинарников.

**Comment by narus2** [comment]
так если v83unpack распарить получаются только тексты, или я ошибаюсь?

**Comment by bytemdfab** [comment]
Посмотрите на https://github.com/xDrivenDevelopment/precommit1c
Там есть флаг для удаления epf после разбора.

**Comment by wizi4d** [comment]
@bytemdfab это почти то, что нужно. Остается вопрос только с получением готового epf после pull в локальный репо.

**Comment by bytemdfab** [comment]
У v8files-extractor.os есть флаг для сборки epf из исходников, в том числе и рекурсивно.

**Comment by wizi4d** [comment]
Ух ты :smile:. @EvilBeaver доделал этот функционал? Надо внедрять значит

**Comment by EvilBeaver** [comment]
@wizi4d доделывал, но не я.

**Comment by nixel2007** [comment]
@wizi4d доделывал,  внезапно, я. Могу скинуть пример батников, собирающих и разбирающих обработки и отчёты рекурсивно.

**Comment by wizi4d** [comment]
Буду очень благодарен!

22:03, Сб, 13.02.2016, Nikita Gryzlov notifications@github.com:

**Comment by nixel2007** [comment]
Имеющаяся структура каталогов:

```
.
libs
processings 
scripts
source

```

Precommit1c подключён как сабмодуль внутри каталога libs. 
Собранные файлы внешних обработок помещаются в каталог processings. Содержимое каталога лежит под игнором, кроме файла .gitkeep
Scripts содержит различные скрипты, в том числе командные файлы по сбору и разбору обработок. 
Source среди прочего содержит каталог processings, в который помещаются разобранные файлы отчетов и обработок. 

Таким образом под гитом у меня хранятся только исходники. Так же есть возможность править файлы исходников, а через скрипт сбора получать готовую обработку. 

Командные файлы запускаются мышкой, двойным кликом.для работы в режиме bat потребуются танцы с определением каталогов и корректным указанием путей. 

Командный файл разбора decompose_processings.cmd

```
chcp 65001
cd ..
oscript -encoding=utf-8 libs/precommit1c/v8files-extractor.os --git-precommit "source" --remove-orig-bin-files
cd scripts
```

Файл сбора build_processings.cmd

```
chcp 65001
oscript -encoding=utf-8 ../libs/precommit1c/v8files-extractor.os --compile "../source/processings" "../processings" --recursive
```

**Comment by wizi4d** [comment]
@nixel2007 подскажи по следующей команде, что не так?

```
oscript "..\utils\precommit1c\v8files-extractor.os" --compile "..\src\tests" "..\tests" --recursive
```

В таргетном каталоге рекурсивно создает вложенные каталоги "tests" до тех пока в длину пути не упирается.
Использую винду.

При этом следующая команда отрабатывает нормально, но только для одного файла:

```
oscript "..\utils\precommit1c\v8files-extractor.os" --compile "..\src\tests\Тесты_МенеджерЗаданий" "..\tests"
```

Есть подозрение, что рекурсивный обход под виндой зацикливается на текущем каталоге "." и его надо явно пропускать.

**Comment by nixel2007** [comment]
@wizi4d 

> В таргетном каталоге рекурсивно создает вложенные каталоги "tests" до тех пока в длину пути не упирается.
> Использую винду.

у меня тоже винда. но почему-то слэши в другую сторону :)
попробуй сделать `cd ..` и выполнить скрипт, как у меня в первом скрипте. я помню, что долго боролся с этой фигней.

**Comment by wizi4d** [comment]
Попробовал вместо относительных путей использовать явное указание каталогов:

```
oscript "C:\Projects\TaskManagerFor1C\utils\precommit1c\v8files-extractor.os" --compile "C:\Projects\TaskManagerFor1C\src\tests" "C:\Projects\TaskManagerFor1C\tests" --recursive
```

Метод `СобратьКаталог` у v8files-extractor.os зацикливается

**Comment by nixel2007** [comment]
можешь дать вывод `tree /f` ? можно в личку на gitter, например

**Comment by EvilBeaver** [comment]
Подкину идею - нет ли в коде НайтиФайлы без второго параметра?

-----Исходное сообщение-----
От: "Nikita Gryzlov" notifications@github.com
Отправлено: ‎25.‎02.‎2016 16:55
Кому: "wizi4d/TaskManagerFor1C" TaskManagerFor1C@noreply.github.com
Копия: "Andrei Ovsiankin" ovsiankin.aa@gmail.com
Тема: Re: [TaskManagerFor1C] Продумать вопрос с отказом от epf внутри репозитория (#7)

можешь дать вывод tree /f ? можно в личку на gitter, например

**Comment by nixel2007** [comment]
@EvilBeaver есть! прямо в функции СобратьКаталог

**Comment by nixel2007** [comment]
@EvilBeaver вижу коммит в ветке мастер односкрипта. надо обновиться? На дев? почему раньше работало? :D

**Comment by EvilBeaver** [comment]
В 12 версии исправили неправильную работу метода НайтиФайлы. Посмотри в закрытых задачах односкрипта. Я писал extractor, полагаясь на неверное поведение

-----Исходное сообщение-----
От: "Nikita Gryzlov" notifications@github.com
Отправлено: ‎25.‎02.‎2016 17:47
Кому: "wizi4d/TaskManagerFor1C" TaskManagerFor1C@noreply.github.com
Копия: "Andrei Ovsiankin" ovsiankin.aa@gmail.com
Тема: Re: [TaskManagerFor1C] Продумать вопрос с отказом от epf внутри репозитория (#7)

@EvilBeaver вижу коммит в ветке мастер односкрипта. надо обновиться? На дев? почему раньше работало? :D

**Comment by nixel2007** [comment]
@EvilBeaver СобратьКаталог() писал я, насколько я помню. Значит, это баг и надо фиксить.

@wizi4d можешь повесить задачу в репо precommit1c?

**Comment by wizi4d** [comment]
@nixel2007 мне рабочий процесс не очень понятен, который ты используешь. Если файлы в processings под игнором, как они захватываются прекоммит хуком?

У себя под тыкание мышкой пока сделал вот что:

```
oscript "..\utils\precommit1c\v8files-extractor.os" --decompile "..\tests" "..\src\tests"
```

**Comment by nixel2007** [comment]
@wizi4d 

> @nixel2007 мне рабочий процесс не очень понятен, который ты используешь. Если файлы в processings под игнором, как они захватываются прекоммит хуком?

`git add -f путь/к/обработке`
